* git checkout, compile, test script:-
pipeline {
    agent any

    stages {
        stage('gitcheckout') {
            steps {
              git branch: 'main', url: 'https://github.com/Putta132/spring-petclinic.git'
            }
        }
        stage('compile'){
            steps{
                sh 'mvn compile'
            }
        }
        stage('test'){
            steps{
                sh 'mvn test'
            }
        }
    }
}

* Sonarqube, package, nexus artifact, tomcat scripts:-

pipeline {
    agent any

    stages {

        stage('gitcheckout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Putta132/spring-petclinic.git'
            }
        }

        stage('generating package') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('sonarqube') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('nexus artifact') {
            steps {

                nexusArtifactUploader(
                    artifacts: [[
                        artifactId: 'spring-boot-starter-parent',
                        classifier: '',
                        file: 'target/spring-petclinic-4.0.0-SNAPSHOT.jar',
                        type: 'jar'
                    ]],

                    credentialsId: 'nexus',
                    groupId: 'org.springframework.boot',
                    nexusUrl: '3.110.205.101:8081',
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    repository: 'spring-pet-clinic',
                    version: 'SNAPSHOT-1.0'
                )
            }
        }

           stage('deploy') {
            steps {

                sshagent(['tomcat-credentials']) {

                    sh '''
                    scp -o StrictHostKeyChecking=no target/spring-petclinic.war ubuntu@3.111.43.129:/home/ubuntu/apache-tomcat-10.1.42/webapps

                    ssh -o StrictHostKeyChecking=no ubuntu@3.111.43.129 /home/ubuntu/apache-tomcat-10.1.42/bin/shutdown.sh

                    ssh -o StrictHostKeyChecking=no ubuntu@3.111.43.129 /home/ubuntu/apache-tomcat-10.1.42/bin/startup.sh
                    '''
                }
            }
        }
    }
}
